# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, verbose_name='slug'),
        ),
    ]
