# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0002_auto_20180421_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('articles', models.ManyToManyField(related_name='recitals', to='gdpr.Article')),
            ],
            options={
                'ordering': ['index'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecitalTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gdpr.Recital')),
            ],
            options={
                'db_table': 'gdpr_recital_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='recitaltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
