# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0004_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='term',
            field=models.CharField(default='', max_length=550),
            preserve_default=False,
        ),
    ]
