# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0005_definition_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='language_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
